server:
  port: 8761
  ssl:
    enabled: false
    key-store: /certs/eureka-keystore.p12
    key-store-password: changeit
    key-store-type: PKCS12
    key-alias: eureka
    #trust-store: classpath:truststore.p12
    #trust-store-password: root123
    #trust-store-type: PKCS12

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false
