version: '3.8'
services:
  eureka1:
    build: ../loggingServiceDiscovery
    container_name: eureka1
    environment:
      - EUREKA_INSTANCE_HOSTNAME=eureka1
      - SERVER_PORT=9091
    ports:
      - "9091:9091"
    networks:
      - logging-net
    deploy:
      restart_policy:
        condition: any

  eureka2:
    build: ../loggingServiceDiscovery
    container_name: eureka2
    environment:
      - EUREKA_INSTANCE_HOSTNAME=eureka2
      - SERVER_PORT=9092
    ports:
      - "9092:9092"
    networks:
      - logging-net
    deploy:
      restart_policy:
        condition: any

networks:
  logging-net:
    driver: bridge
