global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'service-metrics'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'service-a:9464'
          - 'service-b:9464'
