services:
  tempo:
    build: ./tempo
    container_name: tempo
    command: [ "-config.file=/etc/tempo/tempo.yaml" ]
    volumes:
      - tempo-data:/var/tempo
    ports:
      - "4318:4318"   # ✅ OTLP gRPC
      - "4319:4319"   # ✅ OTLP HTTP
      - "3200:3200"   # ✅ Tempo Query API
    networks:
      - obs-net

volumes:
  tempo-data:

networks:
  obs-net:
    external: true
