services:
  promtail:
    build: ./promtail
    container_name: promtail
    networks:
      - obs-net
    volumes:
      - ../logs:/var/log/services:ro                   # mount local folder where log keep to location where log keep inside docker
    command: -config.file=/etc/promtail/promtail.yaml  # promtail-configuration file  
    restart: always

networks:
  obs-net:
    external: true
