server:
  http_listen_port: 3200
  grpc_listen_port: 4317   # internal Tempo port, DO NOT send traces here

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4318   # ✅ OTLP gRPC input
        http:
          endpoint: 0.0.0.0:4319   # ✅ OTLP HTTP input

ingester:
  trace_idle_period: 10s
  max_block_duration: 1h

compactor:
  compaction:
    block_retention: 48h

storage:
  trace:
    backend: local
    local:
      path: /var/tempo/traces
