server:
  port: ${PORT:9091}

eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:eureka1} # dynamically set value pass from docker-compose file we start container
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eurekaadmin:eurekapass@eureka2:9092/eureka/,http://eurekaadmin:eurekapass@eureka3:9093/eureka/}

spring:
  security:
    user:
      name: eurekaadmin
      password: eurekapass