spring:
  kafka:
    bootstrap-servers: localhost:19092,localhost:19093,localhost:19094,localhost:19095,localhost:19096
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      acks: all
      retries: 5
      enable-idempotence: true
      batch-size: 32768
      linger-ms: 50
      compression.type: snappy
      buffer-memory: 33554432
      properties:
        schema.registry.url: http://localhost:8081
      transaction-id-prefix: order-tx-

