spring:
  kafka:
    bootstrap-servers: localhost:19092,localhost:19093,localhost:19094,localhost:19095,localhost:19096
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 5
      enable-idempotence: true
      batch-size: 32768
      linger-ms: 50
      buffer-memory: 33554432
