services:
  nginx:
    build: ./nginx
    container_name: nginx_con
    ports:
      - "80:80"
    networks:
      - infra-net
      - services-net

networks:
  infra-net:
    external: true
  services-net:
    external: true