server:
  port: 8089


eureka:
  instance:
   metadata-map:
      version: 1.0.0
      env: dev
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}